
name: kia_movie
description: "KiaMovie Application for Android and iOS"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Networking
  http: ^1.1.0
  
  # UI Components
  cupertino_icons: ^1.0.6
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  google_fonts: ^6.1.0
  
  # Video Player
  video_player: ^2.8.1
  chewie: ^1.7.1
  
  # Utils
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
